// <auto-generated />
using System;
using Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251102202202_Intialize")]
    partial class Intialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Backend.Entities.EligibleVoter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("IDCardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsNationalMinorityVoter")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NationalMinoritiesEnum")
                        .HasColumnType("integer");

                    b.Property<string>("ResidenceCardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VotingDistinctId")
                        .HasColumnType("uuid");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IDCardNumber")
                        .IsUnique();

                    b.HasIndex("ResidenceCardNumber")
                        .IsUnique();

                    b.HasIndex("VotingDistinctId");

                    b.HasIndex("ZipCode");

                    b.ToTable("EligibleVoters");
                });

            modelBuilder.Entity("Backend.Entities.NationalMinorities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NationalMinoritiesType")
                        .HasColumnType("integer");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NationalMinorities");
                });

            modelBuilder.Entity("Backend.Entities.PartyList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PartyLists");
                });

            modelBuilder.Entity("Backend.Entities.RegisteredNationalMinorityCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NationalMinoritiesId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankInList")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NationalMinoritiesId");

                    b.ToTable("RegisteredNationalMinorityCandidates");
                });

            modelBuilder.Entity("Backend.Entities.RegisteredPartyListCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PartyListId")
                        .HasColumnType("uuid");

                    b.Property<int>("RankInList")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartyListId");

                    b.ToTable("RegisteredPartyListCandidates");
                });

            modelBuilder.Entity("Backend.Entities.SingleMemberCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VotingDistinctId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VotingDistinctId");

                    b.ToTable("SingleMemberCandidates");
                });

            modelBuilder.Entity("Backend.Entities.VoterAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Building")
                        .HasColumnType("text");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Staircase")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("VotingDistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VotingDistrictId");

                    b.ToTable("VoterAddresses");
                });

            modelBuilder.Entity("Backend.Entities.VotingDistrict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OEVK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PollingStationAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PollingStationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TEVK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VotingDistricts");
                });

            modelBuilder.Entity("Backend.Entities.EligibleVoter", b =>
                {
                    b.HasOne("Backend.Entities.VotingDistrict", "VotingDistrict")
                        .WithMany("EligibleVoters")
                        .HasForeignKey("VotingDistinctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotingDistrict");
                });

            modelBuilder.Entity("Backend.Entities.RegisteredNationalMinorityCandidate", b =>
                {
                    b.HasOne("Backend.Entities.NationalMinorities", "NationalMinorities")
                        .WithMany("RegisteredCandidates")
                        .HasForeignKey("NationalMinoritiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NationalMinorities");
                });

            modelBuilder.Entity("Backend.Entities.RegisteredPartyListCandidate", b =>
                {
                    b.HasOne("Backend.Entities.PartyList", "PartyList")
                        .WithMany("RegisteredCandidates")
                        .HasForeignKey("PartyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyList");
                });

            modelBuilder.Entity("Backend.Entities.SingleMemberCandidate", b =>
                {
                    b.HasOne("Backend.Entities.VotingDistrict", "VotingDistrict")
                        .WithMany("SingleMemberCandidates")
                        .HasForeignKey("VotingDistinctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VotingDistrict");
                });

            modelBuilder.Entity("Backend.Entities.VoterAddress", b =>
                {
                    b.HasOne("Backend.Entities.VotingDistrict", null)
                        .WithMany("VoterAddresses")
                        .HasForeignKey("VotingDistrictId");
                });

            modelBuilder.Entity("Backend.Entities.NationalMinorities", b =>
                {
                    b.Navigation("RegisteredCandidates");
                });

            modelBuilder.Entity("Backend.Entities.PartyList", b =>
                {
                    b.Navigation("RegisteredCandidates");
                });

            modelBuilder.Entity("Backend.Entities.VotingDistrict", b =>
                {
                    b.Navigation("EligibleVoters");

                    b.Navigation("SingleMemberCandidates");

                    b.Navigation("VoterAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
